### ISSUE TITLE
Compatibility with 5 inches LCD Display

### ISSUE THREAD

**Issue by alequeiroz** [alw1746/RPI-LCD-STM32#1]
Hello, this is more of a question than a problem with the library, I would like to know if there is a possibility to use this library with any 5 inch display with STM (Bluepill). Thanks.

**Comment by alw1746** [comment]
Most 5" LCD display for RPi use the HDMI interface so this library will not help. There are 5" displays for Arduino that use 16-bit parallel or SPI interface. It is unlikely this library will work without some porting effort as it uses SPI interface on a ILI9486 chip (drivers are very chipset-specific). It might be simpler to port a display vendor's Arduino graphics driver to ST Arduino eg. https://www.ebay.com/itm/302748193881. The main work will be converting ATMEGA328's register operations to STM32 as the drivers typically access port registers directly for speed reasons.
